---
language: generic

os:
  - osx
  - linux

osx_image: Xcode10.1

cache: &mycache
  pip: true
  apt: true
  directories:
    - "${CACHE}"

env:
  global:
    - CACHE="${HOME}/.local"
    - CMAKE_VER=3.12.4
    - CMAKE_URL_STEM="https://cmake.org/files"
    - CTEST_OUTPUT_ON_FAILURE=ON
    - BUILD_TYPES="Release Debug CodeCoverage"
    - PATH="${HOME}/.local/bin:${PATH}"
    - GCCV=8
    - FC=gfortran-${GCCV}
    - CC=gcc-${GCCV}

addons:
  homebrew:
    brewfile: Brewfile.travis
    update: true
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-8
      - gfortran-8
      - python

before_install:
  -  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then .travis.d/install_cmake_${TRAVIS_OS_NAME}.sh ${CMAKE_VER} ${CACHE} ; fi

install:
  - pip install --user -r requirements.txt

script:
  - $FC --version
  - $CC --version
  - cmake --version
  - mkdir build && cd build
  - cmake .. && make -j $(nproc) && ctest --schedule-random --verbose
